### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by edersong** [danielyrovas/linklater#1]
Hello,
Thanks for the invite to test it.
Downloaded, but it's not installing. No errors no messages, just it's not installing
Pixel 6 Android 14

**Comment by danielyrovas** [comment]
Interesting, did you install through the releases?

**Comment by danielyrovas** [comment]
If you have a pc with the [adb](https://developer.android.com/tools/adb) command available, you could try downloading the app from the releases page onto your pc, plugging your phone in (with [USB Debugging](https://www.howtogeek.com/129728/how-to-enable-developer-options-menu-and-enable-and-usb-debugging-on-android/) turned on), and then executing the following command:
```
adb install linklater-release.apk
```

It should give you an error message if it still fails to install.

**Comment by edersong** [comment]
I managed to install it. 
Google Play Protection was blocking because you're not known developer.
Installed, configured but it's not adding links. No errors

**Comment by danielyrovas** [comment]
in your settings I assume you added the LinkDing instance URL and token. Can you make sure the URL has `/api` at the end? so it should look like this for the demo instance:

```
https://demo.linkding.link/api
```
If you are using an IP:

```
http://192.168.0.47:80/api
```

**Comment by edersong** [comment]
With /api it worked fine!

**Comment by danielyrovas** [comment]
Let me know if you have any further issues or suggestions :)
