### ISSUE TITLE
Default options?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [danielyrovas/linklater#2]
Hi,
Thanks for this, works like a charm!
Would you mind adding default options for tags and marking as unread? Similar to the browser extension?
Thanks!

**Comment by danielyrovas** [comment]
As in a configuration option to change whether new bookmarks are saved as `unread` by default?

**Comment by Gandalf-the-Blue** [comment]
Yup, similarly for tags too?

**Comment by danielyrovas** [comment]
alright, I'll add that in the next update.

**Comment by danielyrovas** [comment]
hey @Gandalf-the-Blue can you try the 0.1.7 release? I've added the default tag & flag options.

**Comment by danielyrovas** [comment]
I made a few improvements, and this seems to be working fine for me.
