### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by ma-04** [danielyrovas/linklater#3]
Adding some screenshot would be helpful.

**Comment by danielyrovas** [comment]
Thanks for the feedback, I will setup the screenshots when I complete the play store release.

**Comment by IzzySoft** [comment]
Can you please move the screenshots to the correct location?

* current location: `/fastlane/metadata/android/en-GB/images/`
* correct location: `/fastlane/metadata/android/en-US/images/phoneScreenshots/`

Backgrounds:

* `en-US` is the fallback location for all locales not present
* screenshots go into their specific screenshots directories inside images
* directly inside the `images` directory, you could then also place `icon.png` (min 48x48px, max 512x512px) and a `featureGraphic.png` (512x250 or 1024x500px) – and directly inside the locale directory `short_description.txt` (plain text, single line, max 80 chars) and a `full_description.txt` with max 4,000 chars using e.g. HTML formatting; details on this are outlined in the wiki here: [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane).

Thanks in advance!

And PS, in the "Installation" section of your Readme you can also include your app can be installed (and kept updated) using any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181), as it's available [in the IzzyOnDroid repo here](https://apt.izzysoft.de/packages/org.yrovas.linklater/).

**Comment by danielyrovas** [comment]
Thanks @IzzySoft, I noticed the app got packaged because Droid-ify automatically updated it haha.
I've corrected the screenshot placement, and I'll add the other information when I actually do a Fastlane release.

**Comment by IzzySoft** [comment]
Thanks! Screenshots will then automatically be updated with each release should they have changed. Once you've added other fastlane details (description, icon etc) please give me a ping so I check and enable them here as well.
