### ISSUE TITLE
deleted bookmark

### ISSUE THREAD

**Issue by GulyFMG** [danielyrovas/linklater#5]
Got one more:
Added a link via linklater. Went to linkding and remove the link.
Linklater does not update accordingly.

BTW are you planning on adding similar functions to manage bookmarks in the future? Like remove, manage tags, etc.

**Comment by danielyrovas** [comment]
Yeah this is currently expected behaviour. I will need to add bookmark deletion synchronisation, but its tricky.

I have management functions planned, I will add edit/delete operations. I'm unsure if I will add bulk operations at the moment.

**Comment by danielyrovas** [comment]
Completed in release 1.13
